function ntm_loss = NTM_Loss_single(matdir, net_f, net_w, init_path, N_emp, gamma_in, lambda_in, delta_in, epsilon_in)

beta = 1e-6;
gamma1 = gamma_in;
gamma2 = 0;
%frac = params(4);
frac = 0.7;
lambda1 = lambda_in;
lambda2 = lambda_in;
delta = delta_in;
epsilon = epsilon_in;

L_int = 1000;
L1 = 200;
L2 = 200;
L_ais = 40;
L_syn = 40;
T = 1;
dt = [];
trange = [0:0.0025:0.1, 0.1050:0.005:0.3, 0.31:0.01:1];
resmesh = 'coarse';                             
plotting = 0;
reltol = 1e-4;
abstol = 1e-4;
fsolvetol = 1e-6;
init_rescale = 0.0020;
conn_thresh = 0.8;
use_sr_flux = 0;
use_sr_w1 = 0;

study = 'Hurtado';
connectome_subset = 'Hippocampus+PC+RSP';

sim_no = 1;

%% Run NTM Model

model_output = NetworkTransportModel(matdir,'beta',beta,...
                                'gamma1',gamma1,...
                                'gamma2',gamma2,...
                                'frac',frac,...
                                'lambda1',lambda1,...
                                'lambda2',lambda2,...
                                'delta',delta,...
                                'epsilon',epsilon,...
                                'L_int',L_int,...
                                'L1',L1,...
                                'L2',L2,...
                                'L_ais',L_ais,...
                                'L_syn',L_syn,...,
                                'T',T,...
                                'dt',dt,...
                                'trange',trange,...
                                'resmesh',resmesh,...
                                'plotting',plotting,...
                                'reltol',reltol,...
                                'abstol',abstol,...
                                'fsolvetol',fsolvetol,...
                                'init_rescale',init_rescale,...
                                'init_path',init_path,...
                                'study',study,...
                                'connectome_subset',connectome_subset,...
                                'sim_no',sim_no,...
                                'conn_thresh',conn_thresh,...
                                'use_sr_flux',use_sr_flux,...
                                'use_sr_w1',use_sr_w1,...
                                'use_nn',1,...
                                'net_f',net_f,...
                                'net_w',net_w);

%% Calculate Loss

N_model = model_output.Predicted.N;

ntm_loss = rmse(N_emp, N_model, 'all');




